### ISSUE TITLE
Not working on Android Oreo

### ISSUE THREAD

**Issue by ujeenator** [fullstackreact/react-native-oauth#165]
Facebook login fails with "Sorry something went wrong message"

Google login just hangs after entering the password

**Comment by SailingSteve** [comment]
With 8.0, for me in OAuthManagerModule.java
  private WritableMap accessTokenResponse()
receives a OAuth2AccessToken that looks more like a payload from a URL separated by '&' and the GSON parser crashes on receiving it in about line 404, since the raw response is not JSON, and it would not contain the "user_id" even if it was JSON
Map accessTokenMap = new Gson().fromJson(accessToken.getRawResponse(), Map.class);

**Comment by stuartlangridge** [comment]
I'm seeing possibly the same issue on Android 6.0. Logcat:

```
10-16 10:30:37.892  3051  3051 E AndroidRuntime: FATAL EXCEPTION: main
10-16 10:30:37.892  3051  3051 E AndroidRuntime: Process: (snip), PID: 3051
10-16 10:30:37.892  3051  3051 E AndroidRuntime: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
10-16 10:30:37.892  3051  3051 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:900)
10-16 10:30:37.892  3051  3051 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:853)
10-16 10:30:37.892  3051  3051 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:802)
10-16 10:30:37.892  3051  3051 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:774)
10-16 10:30:37.892  3051  3051 E AndroidRuntime: 	at io.fullstack.oauth.OAuthManagerModule.accessTokenResponse(OAuthManagerModule.java:403)
10-16 10:30:37.892  3051  3051 E AndroidRuntime: 	at io.fullstack.oauth.OAuthManagerModule.access$100(OAuthManagerModule.java:45)
10-16 10:30:37.892  3051  3051 E AndroidRuntime: 	at io.fullstack.oauth.OAuthManagerModule$1.onOAuth1AccessToken(OAuthManagerModule.java:128)
10-16 10:30:37.892  3051  3051 E AndroidRuntime: 	at io.fullstack.oauth.OAuthManagerFragmentController.loaded10aAccessToken(OAuthManagerFragmentController.java:147)
```

I don't think it's OS-specific, although I don't know what the issue actually is.

**Comment by SailingSteve** [comment]
@stuartlangridge  Sorry for the insufficient detail, I was experiencing this on the iOS side.
