### ISSUE TITLE
Authenticating towards Azure AD

### ISSUE THREAD

**Issue by 4xemme** [fullstackreact/react-native-oauth#172]
I have troubles authenticating with AAD. Did anyone try that?

App crashes at the end of the login process

I've configured a new provider passing auth_version (2.0), authorize_url, access_token_url and callback_url (not sure exactly what we need here)

Then on componentDidMount I configure the manager with my own client ID
Later, on a button press, I call authorize with the new provider

I'm presented with all steps where I put my email, get redirected to company login page but when the last step seems to be completed the app crashes

neither reaching then or catch on authorize

**Comment by 4xemme** [comment]
After further investigation I found the following java exception is thrown:

java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract a '"access_token"\s*:\s*"(\S*?)"' from this: ...

somewhere in the body there's a reference to AADSTS90056 error code that, according to MS, seems to result in 'This endpoint only accepts POST requests'

**Comment by magic-overflow** [comment]
Hi there, have you found the solution?

**Comment by msardi23** [comment]
Which package did you end up using for Azure AD? I have had varying success with others but curious to understand which path you ended up going down and how it is working out.

**Comment by sreedhar85in** [comment]
In my case, I was using SoapUI to get the access token from Azure website, and I was using the 'Oauth 2 flow' as Authorization code grant initially. Then while retrieving the token i was getting this error, **"AADSTS90056: This endpoint only accepts POST requests. Received a GET request.".**

 Later I changed the dropdown of  **'Oauth 2 flow'** to '**Client Crendentials Grant**'. After this I immediatley got the access token in the soapui without any error.
